version: '2'
services:
  stfdb:
    image: rethinkdb:2
    ports:
      - 8082:8080
      - 28015:28015
    command: rethinkdb --bind all

  adbd:
    image: sorccu/adb
    ports:
      - 5037:5037
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true

  adb-devices:
    image: sorccu/adb
    tty: true
    links:
      - adbd:adbd
    command: adb -H 172.18.0.1 -P 5037 devices

  stf:
    image: openstf/stf
    ports:
      - 7100:7100
      - 7110:7110
      - "7400-7500:7400-7500"
    links:
      - stfdb:stfdb
      - adbd:adbd
    environment:
      - RETHINKDB_PORT_28015_TCP=tcp://stfdb:28015
      - RETHINKDB_ENV_DATABASE=stf
      - RETHINKDB_ENV_AUTHKEY=admin
    command: stf local --allow-remote --public-ip 192.168.100.21 --provider-min-port 7400 --provider-max-port 7500 --adb-host adbd 
